name: project-monitor

packages:
  - apps/*
  - pkgs/*

command:
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ^3.4.0

    dev_dependencies:
      flutter_lints: ^4.0.0
      test: ^1.25.0

scripts:
  format:
    run: dart format . --line-length 100

  protoc:
    exec: cd protos && protoc --dart_out=grpc:../lib *.proto
    packageFilters:
      dirExists: protos

  build_runner:
    exec: dart run build_runner build
    packageFilters:
      dependsOn: build_runner

  test:
    exec: flutter test

  cyclic_dependency_checks:
    run: dart run cyclic_dependency_checks -m .
