name: somanyfeeds
publish_to: none

environment:
  sdk: ^3.3.0

dev_dependencies:
  melos: ^6.0.0
  cyclic_dependency_checks:
    git: { url: https://github.com/dam5s/cyclic_dependency_checks.git, ref: release/0.6.0 }
