name: networking_support
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  async_support: 0.0.0
  http: ^1.1.0
  logger: ^2.0.2+1
  logging: ^1.2.0
  prelude: 0.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.24.0
