name: project_monitor_server
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.11.0
  async_support: 0.0.0
  collection: ^1.19.0
  freezed_annotation: ^2.4.2
  grpc: ^4.0.0
  hotreloader: ^4.2.0
  logging: ^1.2.0
  networking_support: 0.0.0
  prelude: 0.0.0
  projects_api: 0.0.0

dev_dependencies:
  freezed: ^2.5.4
  flutter_lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
