name: project_monitor_server
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  prelude: 0.0.0
  projects_api: 0.0.0
  logging: ^1.2.0
  grpc: ^3.2.4
  hotreloader: ^4.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.0
